# Generated by Django 5.2.4 on 2025-08-06 14:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vaca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da Vaca (obrigatório)", max_length=100
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, help_text="Data de nascimento (opcional)", null=True
                    ),
                ),
                (
                    "pai",
                    models.CharField(
                        blank=True,
                        help_text="Nome do pai (opcional)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "mae",
                    models.CharField(
                        blank=True,
                        help_text="Nome da mãe (opcional)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "media_producao_diaria",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Média de produção diária de leite em litros.",
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ordenha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Data e hora da ordenha",
                    ),
                ),
                (
                    "quantidade_leite",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantidade de leite em litros",
                        max_digits=5,
                    ),
                ),
                (
                    "vaca",
                    models.ForeignKey(
                        help_text="Vaca que foi ordenhada",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curral.vaca",
                    ),
                ),
            ],
        ),
    ]
