# Generated by Django 5.2.4 on 2025-08-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curral", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vaca",
            name="media_producao_diaria",
        ),
    ]
